# Generated by Django 5.1.1 on 2024-09-16 11:19

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=11, region=None)),
                ('salary', models.IntegerField()),
                ('designation', models.CharField(max_length=50)),
                ('short_description', models.TextField()),
            ],
        ),
    ]
