# Generated by Django 5.1.1 on 2024-09-16 11:35

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_info',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=14, region=None),
        ),
    ]
